[[edge_functions]]
  function = "add-products"
  path = "/add-products"

[[edge_functions]]
  function = "get-products"
  path = "/get-products"
  
[[edge_functions]]
  function = "get-categories"
  path = "/get-categories"

[[edge_functions]]
  function = "add-categories"
  path = "/add-categories"